# Generated by Django 2.1 on 2018-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('facid', models.TextField(max_length=6, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=4)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('office_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('office_section', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=256)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField(max_length=256)),
                ('office_section', models.TextField(max_length=256)),
                ('issue', models.TextField(max_length=256)),
                ('reason', models.TextField(max_length=256)),
                ('proc_appr', models.BooleanField()),
                ('hod_appr', models.BooleanField()),
                ('office_appr', models.BooleanField()),
                ('facid', models.ForeignKey(on_delete='cascade', to='student.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=4)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=256)),
                ('facid', models.ForeignKey(on_delete='cascade', related_name='faculties', to='student.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='requisitions',
            name='usn',
            field=models.ForeignKey(on_delete='cascade', to='student.Student'),
        ),
    ]
