# Generated by Django 2.1 on 2018-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='facid',
            field=models.ForeignKey(on_delete='cascade', to='student.Faculty'),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
