# Generated by Django 2.1 on 2018-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181215_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
