# Generated by Django 2.1 on 2018-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitions',
            name='reqid',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
