# Generated by Django 2.1 on 2018-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181215_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='hod_appr',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='office_appr',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='proc_appr',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
