# Generated by Django 2.1 on 2018-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181215_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitions',
            name='hod_appr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='office_appr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='proc_appr',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
