# Generated by Django 2.1 on 2018-12-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20181215_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitions',
            name='issue',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='requisitions',
            name='office_section',
            field=models.TextField(max_length=30),
        ),
    ]
